// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/zema1/watchvuln/ent/runtime.go

const (
	Version = "v0.12.0"                                         // Version of ent codegen.
	Sum     = "h1:DTub/yd0pMK9s0ONfZps2cYkyD2VPIuknVBv10BESc0=" // Sum of ent codegen.
)
