// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// VulnInformation is the predicate function for vulninformation builders.
type VulnInformation func(*sql.Selector)
